"""Initial migration

Revision ID: c12af9202d0d
Revises: 69bf3ef6802e
Create Date: 2024-11-08 10:43:36.185904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12af9202d0d'
down_revision: Union[str, None] = '69bf3ef6802e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('stories', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stories', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('stories', sa.Column('language', sa.String(), nullable=True))
    op.drop_constraint('stories_user_id_fkey', 'stories', type_='foreignkey')
    op.create_foreign_key(None, 'stories', 'users', ['author_id'], ['id'])
    op.drop_column('stories', 'user_id')
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.add_column('stories', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.create_foreign_key('stories_user_id_fkey', 'stories', 'users', ['user_id'], ['id'])
    op.drop_column('stories', 'language')
    op.drop_column('stories', 'author_id')
    op.drop_column('stories', 'updated_at')
    op.drop_column('stories', 'created_at')
    # ### end Alembic commands ###
